### ISSUE TITLE
gitpull: The message sent is empty or contains invalid characters

### ISSUE THREAD

**Issue by ALiwoto** [ALiwoto/woto-scp#3]
Error logs:
```py
dispatcher.py:253 ERROR: Telegram says: [400 MESSAGE_EMPTY] - The message sent is empty or contains invalid characters (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/ubuntu/aliwoto/projects/py/woto-scp/scp/plugins/user/files.py", line 90, in gitpull
    await r.edit_text(html_mono(str(output)[:4000]), parse_mode=ParseMode.HTML)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2777, in edit_text
    return await self._client.edit_message_text(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 80, in edit_message_text
    r = await self.invoke(
  File "/home/ubuntu/aliwoto/projects/py/woto-scp/scp/core/clients/wotobase.py", line 150, in invoke
    return await super().invoke(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageEmpty: Telegram says: [400 MESSAGE_EMPTY] - The message sent is empty or contains invalid characters (caused by "messages.EditMessage")
```

**References:**
- https://t.me/c/1627169341/1758

**Comment by ALiwoto** [comment]
Issue is here: https://github.com/ALiwoto/woto-scp/blob/b64f5650468863728a693427efb3d817dd0bfc54/scp/plugins/user/files.py#L90

**Comment by ALiwoto** [comment]
the `output` variable here is only stdout, in the case we have an empty string value in stdout, we will encounter this issue.
